service: expense-categorization-api
provider:
  name: aws
  runtime: python3.9
  region: us-east-1
functions:
  api:
    handler: main.app
    events:
      - http:
          path: /
          method: get
